import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex items-center mb-8 gap-8">
          <div className="flex items-center gap-3">
            <img src="/next.svg" alt="Felipoll Logo" className="h-8 w-8" />
            <span className="text-2xl font-bold tracking-tight">Felipoll</span>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 flex-1">
            <a href="/polls" className="bg-card shadow-lg rounded-xl p-6 flex flex-col items-center justify-center hover:bg-primary hover:text-primary-foreground transition font-semibold text-lg">
              <span>Polls</span>
              <span className="text-xs font-normal mt-2 text-muted-foreground">Browse & vote</span>
            </a>
            <a href="/my-polls" className="bg-card shadow-lg rounded-xl p-6 flex flex-col items-center justify-center hover:bg-primary hover:text-primary-foreground transition font-semibold text-lg">
              <span>My Polls</span>
              <span className="text-xs font-normal mt-2 text-muted-foreground">Manage your polls</span>
            </a>
            <a href="/create-poll" className="bg-card shadow-lg rounded-xl p-6 flex flex-col items-center justify-center hover:bg-primary hover:text-primary-foreground transition font-semibold text-lg">
              <span>Create Poll</span>
              <span className="text-xs font-normal mt-2 text-muted-foreground">Start a new poll</span>
            </a>
            <a href="/auth" className="bg-card shadow-lg rounded-xl p-6 flex flex-col items-center justify-center hover:bg-primary hover:text-primary-foreground transition font-semibold text-lg">
              <span>Login/Register</span>
              <span className="text-xs font-normal mt-2 text-muted-foreground">Access your account</span>
            </a>
          </div>
        </nav>
        <main className="max-w-3xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
